/**
* Autogenerated by Service Builder v2.0.8. Do not edit.
* Version: 0.0.1
* Built Fri Apr 21 2023 09:30:20 GMT-0000 (GMT)
* Built to pageName:/OpenForum/AddOn/Tagging fileName:TaggingClient.js
* Example include script: OpenForum.includeScript("/OpenForum/AddOn/Tagging/TaggingClient.js");
**/var TaggingClient = function(host) {
    var self = this;
    self.VERSION = "0.0.0";
    if(!host) host = "";

// get methods

    //Example use: TaggingClient.getTags(  callBack );
    self.getTags = function(  callBack ) {
      OFX.get( host+'/OpenForum/AddOn/Tagging' )
        .withAction( 'getTags' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

    //Example use: TaggingClient.findMatches( type, tag, callBack );
    self.findMatches = function( type, tag, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/Tagging' )
        .withAction( 'findMatches' )
        .withData( {type: type, tag: tag} )
        .onSuccess( callBack ).go();
    };

// End get methods

// post methods

    //Example use: TaggingClient.tag( tag, type, name, wildCard, caseSensitive, callBack );
    self.tag = function( tag, type, name, wildCard, caseSensitive, callBack ) {
      OFX.post( host+'/OpenForum/AddOn/Tagging' )
        .withAction( 'tag' )
        .withData( {tag: tag, type: type, name: name, wildCard: wildCard, caseSensitive: caseSensitive} )
        .onSuccess( callBack ).go();
    };

    //Example use: TaggingClient.addTag( tag, callBack );
    self.addTag = function( tag, callBack ) {
      OFX.post( host+'/OpenForum/AddOn/Tagging' )
        .withAction( 'addTag' )
        .withData( {tag: tag} )
        .onSuccess( callBack ).go();
    };

// End post methods

};
TaggingClient = new TaggingClient();


