/**
* Autogenerated by Service Builder v2.0.8. Do not edit.
* Version: 0.0.2
* Built Wed Mar 22 2023 11:19:48 GMT-0000 (GMT)
* Built to pageName:/Development/ServiceLayer fileName:ServiceLayerClient.js
* Example include script: OpenForum.includeScript("/Development/ServiceLayer/ServiceLayerClient.js");
**/var ServiceLayerClient = function(host) {
    var self = this;
    self.VERSION = "0.0.1";
    if(!host) host = "";

// get methods

    //Example use: ServiceLayerClient.refresh(  callBack );
    self.refresh = function(  callBack ) {
      OFX.get( host+'/Development/ServiceLayer' )
        .withAction( 'refresh' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

    //Example use: ServiceLayerClient.refreshDevelopment(  callBack );
    self.refreshDevelopment = function(  callBack ) {
      OFX.get( host+'/Development/ServiceLayer' )
        .withAction( 'refreshDevelopment' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

    //Example use: ServiceLayerClient.refreshLive(  callBack );
    self.refreshLive = function(  callBack ) {
      OFX.get( host+'/Development/ServiceLayer' )
        .withAction( 'refreshLive' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

    //Example use: ServiceLayerClient.registerServiceObject( pageName, objectName, callBack );
    self.registerServiceObject = function( pageName, objectName, callBack ) {
      OFX.get( host+'/Development/ServiceLayer' )
        .withAction( 'registerServiceObject' )
        .withData( {pageName: pageName, objectName: objectName} )
        .onSuccess( callBack ).go();
    };

// End get methods

// post methods



// End post methods

};
ServiceLayerClient = new ServiceLayerClient();

