/**
* Autogenerated by Service Builder v2.0.5. Do not edit.
* Version: 1.1.1
* Built Wed Nov 16 2022 21:22:05 GMT-0000 (GMT)
* Built to pageName:/OpenForum/AddOn/Publisher fileName:PublisherClient.js
* Example include script: OpenForum.includeScript("/OpenForum/AddOn/Publisher/PublisherClient.js");
**/var PublisherClient = function(host) {
    var self = this;
    self.VERSION = "1.1.1";
    if(!host) host = "";

// get methods

    //Example use: PublisherClient.publish( pageName, practice, debug, callBack );
    self.publish = function( pageName, practice, debug, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/Publisher' )
        .withAction( 'publish' )
        .withData( {pageName: pageName, practice: practice, debug: debug} )
        .onSuccess( callBack ).go();
    };

    //Example use: PublisherClient.getNeedsPublishing( pageName, callBack );
    self.getNeedsPublishing = function( pageName, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/Publisher' )
        .withAction( 'getNeedsPublishing' )
        .withData( {pageName: pageName} )
        .onSuccess( callBack ).go();
    };

    //Example use: PublisherClient.getPublishedPageDifferences( pageName, callBack );
    self.getPublishedPageDifferences = function( pageName, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/Publisher' )
        .withAction( 'getPublishedPageDifferences' )
        .withData( {pageName: pageName} )
        .onSuccess( callBack ).go();
    };

    //Example use: PublisherClient.reversePublish( pageName, callBack );
    self.reversePublish = function( pageName, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/Publisher' )
        .withAction( 'reversePublish' )
        .withData( {pageName: pageName} )
        .onSuccess( callBack ).go();
    };

// End get methods

// post methods



// End post methods

};
PublisherClient = new PublisherClient();


