/**
* Autogenerated by Plugin Builder v0.0.1. Do not edit.
* Built Tue Aug 17 2021 14:18:30 GMT-0000 (GMT)
* Built to pageName:/OpenForum/AddOn/SQL/SQLPlugin fileName:plugin.js
**/
if( typeof SQLPlugin === "undefined" ) {
  
var SQLPlugin = {
  open: false,
  close: function() {
    SQLPlugin.open = false;
  }
};

addPlugin( {
  name: "SQL Plugin",
  editorIndex: 0,
  init: function() {
    if(SQLPlugin.open===true) {
      return;
    }
    SQLPlugin.open=true;
    editorIndex++;
    this.editorIndex = editorIndex;
    var editor = document.createElement("div");
    editor.setAttribute("id","editor"+editorIndex);
    editor.setAttribute("style","display:block;");
    document.getElementById("editors").appendChild(editor);

    OpenForum.crawl(document.getElementById("editor"+editorIndex));

    var content = OpenForum.loadFile("/OpenForum/Actions/RenderWikiData?pageName=" + pageName + "&sourcePageName=/OpenForum/AddOn/SQL&fileName=page.content");
    OpenForum.setElement("editor"+editorIndex,content);    

    OpenForum.crawl(document.getElementById("editor"+editorIndex));

    DependencyService.createNewDependency()
    .addDependency("/OpenForum/AddOn/SQL/sql-editor.js")
    .addDependency("/OpenForum/AddOn/SQL/DB.js")
    .addDependency("/OpenForum/Javascript/FluentTemplateProcessor/FluentTemplateProcessor.js")
    .setOnLoadTrigger( function() {
      SQLEditorController.init(); SQLEditorController.initEditor();
    } ).loadDependencies();

    OpenForum.addTab("editor"+editorIndex);
    editorList[editorIndex] = {id: editorIndex, tabButtonStyle: "tab", tabId: "editor"+editorIndex, name: "SQL Plugin", changed: "", plugin: SQLPlugin};
    showTab(editorIndex);
    return editorList[editorIndex];

  },
  run: function(tabName) {
    new Process().waitFor( function() { return (typeof SQLEditorController!="undefined"); } ).then( function() {
    var sqlScript = findEditor(tabName.trim()).editor.getValue();
    SQLEditorController.setScript( sqlScript );
    SQLEditorController.runSQLScript();
    }).run();
  }
});

} else {
  for(var i in editorList) {
    if(editorList[i].name==="SQL Plugin") {
      showTab( editorList[i].id );
      break;
    }
  }
}
