/**
* Autogenerated by Service Builder v2.0.5. Do not edit.
* Version: 0.0.4
* Built Sun Nov 13 2022 19:31:45 GMT-0000 (GMT)
* Built to pageName:/OpenForum/Actions/Access fileName:AccessClient.js
* Example include script: OpenForum.includeScript("/OpenForum/Actions/Access/AccessClient.js");
**/var AccessClient = function(host) {
    var self = this;
    self.VERSION = "0.0.4";
    if(!host) host = "";

// get methods



// End get methods

// post methods

    //Example use: AccessClient.getAccess( pageName, callBack );
    self.getAccess = function( pageName, callBack ) {
      OFX.post( host+'/OpenForum/Actions/Access' )
        .withAction( 'getAccess' )
        .withData( {pageName: pageName} )
        .onSuccess( callBack ).go();
    };

// End post methods

};
AccessClient = new AccessClient();

