/**
* Autogenerated by Service Builder v2.0.8. Do not edit.
* Version: 1.0.4
* Built Sun Apr 23 2023 12:26:15 GMT-0000 (GMT)
* Built to pageName:/OpenForum/Triggers/TimerTrigger/TaskScheduler fileName:TaskSchedulerClient.js
* Example include script: OpenForum.includeScript("/OpenForum/Triggers/TimerTrigger/TaskScheduler/TaskSchedulerClient.js");
**/var TaskSchedulerClient = function(host) {
    var self = this;
    self.VERSION = "1.0.3";
    if(!host) host = "";

// get methods

    //Example use: TaskSchedulerClient.getSchedule( tag, callBack );
    self.getSchedule = function( tag, callBack ) {
      OFX.get( host+'/OpenForum/Triggers/TimerTrigger/TaskScheduler' )
        .withAction( 'getSchedule' )
        .withData( {tag: tag} )
        .onSuccess( callBack ).go();
    };

    //Example use: TaskSchedulerClient.addTask( name, enabled, debug, pagename, scriptfile, lastrun, scheduledtime, callBack );
    self.addTask = function( name, enabled, debug, pagename, scriptfile, lastrun, scheduledtime, callBack ) {
      OFX.get( host+'/OpenForum/Triggers/TimerTrigger/TaskScheduler' )
        .withAction( 'addTask' )
        .withData( {name: name, enabled: enabled, debug: debug, pagename: pagename, scriptfile: scriptfile, lastrun: lastrun, scheduledtime: scheduledtime} )
        .onSuccess( callBack ).go();
    };

    //Example use: TaskSchedulerClient.deleteTask( taskName, callBack );
    self.deleteTask = function( taskName, callBack ) {
      OFX.get( host+'/OpenForum/Triggers/TimerTrigger/TaskScheduler' )
        .withAction( 'deleteTask' )
        .withData( {taskName: taskName} )
        .onSuccess( callBack ).go();
    };

    //Example use: TaskSchedulerClient.runTrigger( pageName, triggerFile, callBack );
    self.runTrigger = function( pageName, triggerFile, callBack ) {
      OFX.get( host+'/OpenForum/Triggers/TimerTrigger/TaskScheduler' )
        .withAction( 'runTrigger' )
        .withData( {pageName: pageName, triggerFile: triggerFile} )
        .onSuccess( callBack ).go();
    };

// End get methods

// post methods



// End post methods

};
TaskSchedulerClient = new TaskSchedulerClient();

