/**
* Autogenerated by Service Builder v2.0.8. Do not edit.
* Version: 0.0.5
* Built Wed Jun 21 2023 09:00:07 GMT-0000 (GMT)
* Built to pageName:/OpenForum/AddOn/DataLogger/PageAccessMonitor fileName:PageAccessMonitorClient.js
* Example include script: OpenForum.includeScript("/OpenForum/AddOn/DataLogger/PageAccessMonitor/PageAccessMonitorClient.js");
**/
var PageAccessMonitorClient = function(host) {
    var self = this;
    self.VERSION = "0.0.0";
    if(!host) host = "";

// get methods

    //Example use: PageAccessMonitorClient.getPageAccessData( site, pageName, callBack );
    self.getPageAccessData = function( site, pageName, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/DataLogger/PageAccessMonitor' )
        .withAction( 'getPageAccessData' )
        .withData( {site: site, pageName: pageName} )
        .onSuccess( callBack ).go();
    };

    //Example use: PageAccessMonitorClient.getSiteAccesData(  callBack );
    self.getSiteAccesData = function(  callBack ) {
      OFX.get( host+'/OpenForum/AddOn/DataLogger/PageAccessMonitor' )
        .withAction( 'getSiteAccesData' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

// End get methods

// post methods

    //Example use: PageAccessMonitorClient.logPageAccess( site, pages, callBack );
    self.logPageAccess = function( site, pages, callBack ) {
      OFX.post( host+'/OpenForum/AddOn/DataLogger/PageAccessMonitor' )
        .withAction( 'logPageAccess' )
        .withData( {site: site, pages: pages} )
        .onSuccess( callBack ).go();
    };

    //Example use: PageAccessMonitorClient.logUserJourney( currentPage, referrer, userAgent, callBack );
    self.logUserJourney = function( currentPage, referrer, userAgent, callBack ) {
      OFX.post( host+'/OpenForum/AddOn/DataLogger/PageAccessMonitor' )
        .withAction( 'logUserJourney' )
        .withData( {currentPage: currentPage, referrer: referrer, userAgent: userAgent} )
        .onSuccess( callBack ).go();
    };

// End post methods

};
PageAccessMonitorClient = new PageAccessMonitorClient();

