/**
* Autogenerated by Service Builder v2.0.8. Do not edit.
* Version: 0.0.5
* Built Wed Jun 21 2023 09:08:00 GMT-0000 (GMT)
* Built to pageName:/OpenForum/Actions/User fileName:UserClient.js
* Example include script: OpenForum.includeScript("/OpenForum/Actions/User/UserClient.js");
**/var UserClient = function(host) {
    var self = this;
    self.VERSION = "0.0.0";
    if(!host) host = "";

// get methods

    //Example use: UserClient.getCurrentUser( currentPage, referrer, userAgent, callBack );
    self.getCurrentUser = function( currentPage, referrer, userAgent, callBack ) {
      OFX.get( host+'/OpenForum/Actions/User' )
        .withAction( 'getCurrentUser' )
        .withData( {currentPage: currentPage, referrer: referrer, userAgent: userAgent} )
        .onSuccess( callBack ).go();
    };

    //Example use: UserClient.getCurrentUserProfile(  callBack );
    self.getCurrentUserProfile = function(  callBack ) {
      OFX.get( host+'/OpenForum/Actions/User' )
        .withAction( 'getCurrentUserProfile' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

// End get methods

// post methods



// End post methods

};
UserClient = new UserClient();


