/**
* Autogenerated by Service Builder v2.0.4. Do not edit.
* Version: 0.1.4
* Built Fri Aug 27 2021 12:51:46 GMT-0000 (GMT)
* Built to pageName:/OpenForum/AddOn/ContentEditor fileName:ContentEditorClient.js
* Example include script: OpenForum.includeScript("/OpenForum/AddOn/ContentEditor/ContentEditorClient.js");
**/var ContentEditorClient = function(host) {
    var self = this;
    self.VERSION = "0.0.1";
    if(!host) host = "";

// get methods

    //Example use: ContentEditorClient.getPages(  callBack );
    self.getPages = function(  callBack ) {
      OFX.get( host+'/OpenForum/AddOn/ContentEditor' )
        .withAction( 'getPages' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

    //Example use: ContentEditorClient.getBlockEditors(  callBack );
    self.getBlockEditors = function(  callBack ) {
      OFX.get( host+'/OpenForum/AddOn/ContentEditor' )
        .withAction( 'getBlockEditors' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

    //Example use: ContentEditorClient.convertPage( targetPageName, callBack );
    self.convertPage = function( targetPageName, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/ContentEditor' )
        .withAction( 'convertPage' )
        .withData( {targetPageName: targetPageName} )
        .onSuccess( callBack ).go();
    };

    //Example use: ContentEditorClient.convertHTMLPage( targetPageName, callBack );
    self.convertHTMLPage = function( targetPageName, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/ContentEditor' )
        .withAction( 'convertHTMLPage' )
        .withData( {targetPageName: targetPageName} )
        .onSuccess( callBack ).go();
    };

// End get methods

// post methods



// End post methods

};
ContentEditorClient = new ContentEditorClient();


