/**
* Autogenerated by Service Builder v2.0.5. Do not edit.
* Version: 0.0.1
* Built Thu Nov 17 2022 19:42:06 GMT-0000 (GMT)
* Built to pageName:/OpenForum/Actions/History fileName:HistoryClient.js
* Example include script: OpenForum.includeScript("/OpenForum/Actions/History/HistoryClient.js");
**/var HistoryClient = function(host) {
    var self = this;
    self.VERSION = "0.0.0";
    if(!host) host = "";

// get methods

    //Example use: HistoryClient.list( pageName, fileName, callBack );
    self.list = function( pageName, fileName, callBack ) {
      OFX.get( host+'/OpenForum/Actions/History' )
        .withAction( 'list' )
        .withData( {pageName: pageName, fileName: fileName} )
        .onSuccess( callBack ).go();
    };

// End get methods

// post methods



// End post methods

};
HistoryClient = new HistoryClient();


