/**
* Autogenerated by Service Builder v2.0.8. Do not edit.
* Version: 0.1.9
* Built Mon Dec 19 2022 11:05:46 GMT-0000 (GMT)
* Built to pageName:/OpenForum/AddOn/Update fileName:UpdateClient.js
* Example include script: OpenForum.includeScript("/OpenForum/AddOn/Update/UpdateClient.js");
**/

var UpdateClient = function(host) {
  var self = this;
  self.VERSION = "0.0.4";
  if(!host) host = "";

  // get methods

    //Example use: UpdateClient.getUpdate( action, pageName, ignoreChanges, callBack );
    self.getUpdate = function( action, pageName, ignoreChanges, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/Update' )
        .withAction( 'getUpdate' )
        .withData( {action: action, pageName: pageName, ignoreChanges: ignoreChanges} )
        .onSuccess( callBack ).go();
    };

    //Example use: UpdateClient.getUpdateInfo( action, pageName, callBack );
    self.getUpdateInfo = function( action, pageName, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/Update' )
        .withAction( 'getUpdateInfo' )
        .withData( {action: action, pageName: pageName} )
        .onSuccess( callBack ).go();
    };

    //Example use: UpdateClient.getReleases( action, callBack );
    self.getReleases = function( action, callBack ) {
      OFX.get( host+'/OpenForum/AddOn/Update' )
        .withAction( 'getReleases' )
        .withData( {action: action} )
        .onSuccess( callBack ).go();
    };

// End get methods

  // post methods

    //Example use: UpdateClient.upsertToJSONList( action, row, indexName, pageName, fileName, callBack );
    self.upsertToJSONList = function( action, row, indexName, pageName, fileName, callBack ) {
      OFX.post( host+'/OpenForum/AddOn/Update' )
        .withAction( 'upsertToJSONList' )
        .withData( {action: action, row: row, indexName: indexName, pageName: pageName, fileName: fileName} )
        .onSuccess( callBack ).go();
    };

// End post methods
};
UpdateClient = new UpdateClient();

