/**
* Autogenerated by Service Builder v2.0.8. Do not edit.
* Version: 0.0.2
* Built Thu Jul 13 2023 10:08:01 GMT-0000 (GMT)
* Built to pageName:/OpenForum/Triggers/TimerTrigger/TaskScheduler/Logs fileName:LogsClient.js
* Example include script: OpenForum.includeScript("/OpenForum/Triggers/TimerTrigger/TaskScheduler/Logs/LogsClient.js");
**/
var LogsClient = function(host) {
    var self = this;
    self.VERSION = "0.0.1";
    if(!host) host = "";

// get methods

    //Example use: LogsClient.getTaskSchedulerTime(  callBack );
    self.getTaskSchedulerTime = function(  callBack ) {
      OFX.get( host+'/OpenForum/Triggers/TimerTrigger/TaskScheduler/Logs' )
        .withAction( 'getTaskSchedulerTime' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

    //Example use: LogsClient.getScheduleView(  callBack );
    self.getScheduleView = function(  callBack ) {
      OFX.get( host+'/OpenForum/Triggers/TimerTrigger/TaskScheduler/Logs' )
        .withAction( 'getScheduleView' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

// End get methods

// post methods



// End post methods

};
LogsClient = new LogsClient();

