/**
* Autogenerated by Service Builder v2.0.5. Do not edit.
* Version: 0.0.2
* Built Sun Nov 13 2022 19:58:27 GMT-0000 (GMT)
* Built to pageName:/OpenForum/Actions/GetAttachments fileName:GetAttachmentsClient.js
* Example include script: OpenForum.includeScript("/OpenForum/Actions/GetAttachments/GetAttachmentsClient.js");
**/var GetAttachmentsClient = function(host) {
    var self = this;
    self.VERSION = "0.0.1";
    if(!host) host = "";

// get methods

    //Example use: GetAttachmentsClient.getMatching( matching, callBack );
    self.getMatching = function( matching, callBack ) {
      OFX.get( host+'/OpenForum/Actions/GetAttachments' )
        .withAction( 'getMatching' )
        .withData( {matching: matching} )
        .onSuccess( callBack ).go();
    };

    //Example use: GetAttachmentsClient.getAll(  callBack );
    self.getAll = function(  callBack ) {
      OFX.get( host+'/OpenForum/Actions/GetAttachments' )
        .withAction( 'getAll' )
        .withData( {} )
        .onSuccess( callBack ).go();
    };

// End get methods

// post methods



// End post methods

};
GetAttachmentsClient = new GetAttachmentsClient();

