/**
* Autogenerated by Service Builder v2.0.8. Do not edit.
* Version: 0.0.3
* Built Thu Jun 22 2023 10:02:49 GMT-0000 (GMT)
* Built to pageName:/OpenForum/AddOn/DataLogger/BrowserErrorLogger fileName:BrowserErrorLoggerClient.js
* Example include script: OpenForum.includeScript("/OpenForum/AddOn/DataLogger/BrowserErrorLogger/BrowserErrorLoggerClient.js");
**/r BrowserErrorLogerClient = function(host) {
    var self = this;
    self.VERSION = "0.0.1";
    if(!host) host = "";

// post methods

    //Example use: BrowserErrorLoggerClient.logError( site, page, error, origin, callBack );
    self.logError = function( site, page, error, origin, callBack ) {
      OFX.post( host+'/OpenForum/AddOn/DataLogger/BrowserErrorLogger' )
        .withAction( 'logError' )
        .withData( {site: site, page: page, error: error, origin: origin} )
        .onSuccess( callBack ).go();
    };

// End post methods

};
BrowserErrorLogerClient = new BrowserErrorLogerClient();

